export const TELEMETRY_EVENT_ACTIVATION = 'activation'
export const TELEMETRY_EVENT_SHOW_SOURCE = 'showSource'
export const TELEMETRY_EVENT_SHOW_PREVIEW = 'showPreview'
export const TELEMETRY_EVENT_SHOW_PREVIEW_TO_SIDE = 'showPreviewToSide'
export const TELEMETRY_EVENT_SHOW_PREVIEW_EDITOR = 'showPreviewEditor'
export const TELEMETRY_EVENT_TOGGLE_BOUNDING_BOX = 'changeBoundingBoxVisibility'
export const TELEMETRY_EVENT_TOGGLE_TRANSPARENCY_GRID = 'changeTransparencyGridVisibility'
